module.exports = {
    USER_REGISTER:'USER_REGISTER',
    USER_LOGIN:'USER_LOGIN',
    USER_CONNECTED:'USER_CONNECTED',
    LOG_OUT:'LOG_OUT',
    PRIVATE_MESSAGE:'PRIVATE_MESSAGE',
    SENT_MESSAGE:'SENT_MESSAGE',
    MESSAGE_RECIEVED:'MESSAGE_RECIEVED',
    CONNECTED_USERS:'CONNECTED_USERS',
    GROUP_MESSAGE:'GROUP_MESSAGE',
    ALL_USERS:'ALL_USERS',
    DELETE_CHAT:'DELETE_CHAT',
}